name: Build, Push, and Deploy Docker Container

on:
  push:
    branches:
      - main # Trigger on main branch push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t andreo141/astro-portfolio:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push andreo141/astro-portfolio:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH using Tailscale
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/docker/portfolio
            drc pull
            drc down --remove-orphans
            drc rm portfolio
            drc up -d
